"""
CTS Full End-to-End Test Suite
================================
Total cheques : 32  (12 Outward · 20 Inward)
Order         : OUTWARD always first, then INWARD
Infrastructure: zero — runs purely in-process via run_with_mocks()
Mocked        : vLLM inference outputs · NGCH push
Tested        : all workflow routing, STP-mode, CBS/account/stop-payment/
                IFSC/series/fraud/signature/alteration/security-features
                gates; IET watchdog spawn; SMB side-effects; audit trail

Run:
    pytest tests/e2e/cts/ -v
Report:
    test-reports/latest.html   (auto-generated by root conftest.py)

Delta workflow:
    Add one row to OUTWARD_FIXTURES or INWARD_FIXTURES in cheque_fixtures.py
    → re-run → only the new scenario is red/green; rest unchanged.
"""
from __future__ import annotations

import time
from unittest.mock import AsyncMock, patch

import pytest

from modules.cts.workflows.cheque_workflow import (
    ChequeProcessingWorkflow,
    ChequeWorkflowInput,
)
from modules.cts.workflows.outward_scan_workflow import (
    OutwardScanWorkflow,
    OutwardScanInput,
)

from tests.e2e.cts.cheque_fixtures import (
    INWARD_FIXTURES,
    INWARD_COUNT,
    OUTWARD_COUNT,
    OUTWARD_FIXTURES,
    TOTAL_CHEQUES,
    fresh_iet_deadline,
)
from tests.e2e.cts.mock_builders import (
    build_inward_mocks,
    build_inward_step_trace,
    build_outward_mocks,
    build_outward_step_trace,
)


# ─────────────────────────────────────────────────────────────────────────────
# Suite banner  (printed once at collection time)
# ─────────────────────────────────────────────────────────────────────────────

def pytest_configure(config):                                    # noqa: ARG001
    print(
        f"\n{'─'*60}\n"
        f"  CTS E2E Suite  |  {TOTAL_CHEQUES} cheques total\n"
        f"  Outward: {OUTWARD_COUNT}  ·  Inward: {INWARD_COUNT}\n"
        f"  Languages: EN · HI · MR · TA · TE · KN · GU · BN · ML\n"
        f"             + Bilingual (EN+HI · EN+MR · EN+KN · EN+TA)\n"
        f"  Mocked: vLLM inference · NGCH push\n"
        f"{'─'*60}"
    )


# ─────────────────────────────────────────────────────────────────────────────
# Helper: build OutwardScanInput from fixture
# ─────────────────────────────────────────────────────────────────────────────

def _build_outward_input(fixture) -> OutwardScanInput:           # noqa: ANN001
    image_base = f"https://minio.internal/cts/e2e/{fixture.fixture_id}"
    return OutwardScanInput(
        scan_id=fixture.scan_id or f"SCAN-{fixture.fixture_id}-20260824",
        instrument_id=fixture.instrument_id,
        bank_id=fixture.bank_id,
        bank_ifsc=fixture.bank_ifsc,
        session_id=fixture.session_id,
        image_front_url=f"{image_base}-front.tif",
        image_rear_url=f"{image_base}-rear.tif",
        cheque_number=fixture.cheque_number,
        front_dpi=200,
        rear_dpi=200,
        front_colour_depth=24,
        rear_colour_depth=24,
        branch_id=fixture.branch_id,
        payee_account_number=fixture.payee_account_number,
        payee_name_from_slip=getattr(fixture, "payee_name_from_slip", None),
        image_front_gray_url=f"{image_base}-front-gray.tif" if fixture.has_gray_image else None,
        image_uv_url=f"{image_base}-uv.tif" if fixture.has_uv_image else None,
        registered_drawee_ifsc=getattr(fixture, "registered_drawee_ifsc", None),
    )


# ─────────────────────────────────────────────────────────────────────────────
# Helper: build ChequeWorkflowInput from fixture
# ─────────────────────────────────────────────────────────────────────────────

def _build_inward_input(fixture) -> ChequeWorkflowInput:         # noqa: ANN001
    return ChequeWorkflowInput(
        instrument_id=fixture.instrument_id,
        bank_id=fixture.bank_id,
        image_url=f"https://minio.internal/cts/e2e/{fixture.fixture_id}-front.tif",
        account_number=fixture.account_number,
        cheque_number=fixture.cheque_number,
        presented_amount=fixture.amount,
        presented_payee=fixture.payee_name,
        iet_deadline=fresh_iet_deadline(),
        smb_id=fixture.smb_id,
        ngch_ifsc=fixture.ngch_ifsc,
        cts_config=fixture.cts_config,
    )


# ─────────────────────────────────────────────────────────────────────────────
# OUTWARD — 12 cheques
# Scenarios: 3 ACCEPTED (+ve) · 1 POST_DATED_HELD · 2 CTS_REJECTED (date/compliance)
#            1 CTS_REJECTED (NGCH) · 1 CTS_REJECTED (payee) · 4 MISMATCH_HELD
# ─────────────────────────────────────────────────────────────────────────────

@pytest.mark.asyncio
@pytest.mark.parametrize(
    "fixture",
    OUTWARD_FIXTURES,
    ids=[f.fixture_id for f in OUTWARD_FIXTURES],
)
async def test_outward_e2e(fixture, register_instrument):
    """
    Outward pipeline E2E.
    Checklist: pipeline registry outward steps verified per cheque.
    Outcome captured in test-reports/latest.html Digest.
    """
    wf = OutwardScanWorkflow()
    inp = _build_outward_input(fixture)
    mocks = build_outward_mocks(fixture)

    t0 = time.perf_counter()
    result = await wf.run_with_mocks(inp, mocks)
    duration_ms = int((time.perf_counter() - t0) * 1000)

    # ── Core assertion: outcome matches expected ──────────────────────────────
    assert result.outcome == fixture.expected_outcome, (
        f"[{fixture.fixture_id}] {fixture.language} · {fixture.scenario}\n"
        f"  Expected outcome : {fixture.expected_outcome}\n"
        f"  Actual outcome   : {result.outcome}\n"
        f"  Trigger          : {fixture.trigger}\n"
        f"  Violations       : {result.violations}"
    )

    # ── Audit must always be written ─────────────────────────────────────────
    assert result.audit_written is True, (
        f"[{fixture.fixture_id}] audit_written must be True for all outcomes"
    )

    # ── Outcome-specific assertions ───────────────────────────────────────────
    if result.outcome == "MISMATCH_HELD":
        assert result.mismatch_fields is not None and len(result.mismatch_fields) > 0, (
            f"[{fixture.fixture_id}] MISMATCH_HELD must carry mismatch_fields"
        )

    if result.outcome == "CTS_REJECTED":
        assert result.violations is not None and len(result.violations) > 0, (
            f"[{fixture.fixture_id}] CTS_REJECTED must carry at least one violation"
        )

    if fixture.trigger in ("POST_DATED", "STALE_DATE"):
        assert result.outcome in ("POST_DATED_HELD", "CTS_REJECTED"), (
            f"[{fixture.fixture_id}] Date violations must exit at date-check step"
        )

    # ── Build checklist step trace ────────────────────────────────────────────
    steps = build_outward_step_trace(fixture)

    # Checklist assertion: at minimum 2 steps must appear in trace
    assert len(steps) >= 2, (
        f"[{fixture.fixture_id}] Step trace has only {len(steps)} steps — too short"
    )

    # ── Register in Digest ────────────────────────────────────────────────────
    register_instrument(
        instrument_id=fixture.instrument_id,
        bank_id=fixture.bank_id,
        workflow_type="OUTWARD",
        decision=result.outcome,
        rationale=f"{fixture.trigger} | violations={result.violations or []}",
        steps=steps,
        amount_range=fixture.amount_range,
        duration_ms=duration_ms,
        test_name=f"test_outward_e2e[{fixture.fixture_id}]",
    )


# ─────────────────────────────────────────────────────────────────────────────
# INWARD — 20 cheques
# Scenarios: 3 STP_CONFIRM (+ve) · 5 STP_RETURN · 12 HUMAN_REVIEW
# ─────────────────────────────────────────────────────────────────────────────

@pytest.mark.asyncio
@pytest.mark.parametrize(
    "fixture",
    INWARD_FIXTURES,
    ids=[f.fixture_id for f in INWARD_FIXTURES],
)
async def test_inward_e2e(fixture, register_instrument):
    """
    Inward pipeline E2E.
    Checklist: all 24 pipeline registry steps verified per cheque.
    IET watchdog spawn confirmed on every cheque (non-negotiable).
    Outcome captured in test-reports/latest.html Digest.
    """
    wf = ChequeProcessingWorkflow()
    inp = _build_inward_input(fixture)
    mocks = build_inward_mocks(fixture)

    watchdog_log: list[dict] = []

    async def _on_watchdog_spawn(watchdog_id: str, iet_deadline: float) -> None:
        watchdog_log.append({"watchdog_id": watchdog_id, "iet_deadline": iet_deadline})

    t0 = time.perf_counter()

    # Always patch SMB activities — they call real infra in production;
    # here we just verify they were (or were not) called.
    with (
        patch(
            "modules.cts.workflows.cheque_workflow.notify_sub_member_return",
            new_callable=AsyncMock,
        ) as mock_notify,
        patch(
            "modules.cts.workflows.cheque_workflow.emit_batch_ledger_update",
            new_callable=AsyncMock,
        ) as mock_ledger,
    ):
        result = await wf.run_with_mocks(
            inp, mocks, on_watchdog_spawn=_on_watchdog_spawn
        )

    duration_ms = int((time.perf_counter() - t0) * 1000)

    # ── IET watchdog: must spawn BEFORE any processing (non-negotiable) ───────
    assert len(watchdog_log) == 1, (
        f"[{fixture.fixture_id}] IET watchdog must be spawned exactly once; "
        f"got {len(watchdog_log)}"
    )
    assert watchdog_log[0]["watchdog_id"] == (
        f"cts-iet-{fixture.bank_id}-{fixture.instrument_id}"
    ), (
        f"[{fixture.fixture_id}] Watchdog ID format wrong: {watchdog_log[0]['watchdog_id']}"
    )
    assert watchdog_log[0]["iet_deadline"] > time.time(), (
        f"[{fixture.fixture_id}] IET deadline must be in the future"
    )

    # ── Core assertion: decision matches expected ─────────────────────────────
    assert result.decision == fixture.expected_outcome, (
        f"[{fixture.fixture_id}] {fixture.language} · {fixture.scenario}\n"
        f"  Expected decision : {fixture.expected_outcome}\n"
        f"  Actual decision   : {result.decision}\n"
        f"  Rationale         : {result.rationale}\n"
        f"  Trigger           : {fixture.trigger}"
    )

    # ── Polarity contract ─────────────────────────────────────────────────────
    if fixture.polarity == "POSITIVE":
        assert result.decision == "STP_CONFIRM", (
            f"[{fixture.fixture_id}] POSITIVE scenario must yield STP_CONFIRM"
        )
    else:
        assert result.decision in ("STP_RETURN", "HUMAN_REVIEW"), (
            f"[{fixture.fixture_id}] NEGATIVE scenario must yield STP_RETURN or HUMAN_REVIEW"
        )

    # ── STP_FULL_MANUAL: AI recommended CONFIRM, mode forced HUMAN_REVIEW ─────
    if fixture.trigger == "STP_FULL_MANUAL":
        assert result.stp_eligible is True, (
            f"[{fixture.fixture_id}] stp_eligible must be True when FULL_MANUAL downgrades"
        )
        assert result.ai_recommendation == "CONFIRM", (
            f"[{fixture.fixture_id}] ai_recommendation must be CONFIRM in FULL_MANUAL mode"
        )

    # ── SMB side-effects ──────────────────────────────────────────────────────
    # Early-exit scenarios (before SMB section) must NOT call SMB activities.
    # Only ALL_PASS_SMB reaches the SMB section.
    _early_exit_triggers = {
        "OCR_LOW_CONF", "ALTERATION", "SECURITY_FEAT_FAIL", "CTS2010_FAIL",
        "STOP_PAYMENT_STP", "STOP_PAYMENT_BLOOM", "IFSC_INVALID",
        "CHEQUE_SERIES_STP", "CBS_INSUFFICIENT", "CBS_UNAVAILABLE",
        "ACCOUNT_FROZEN", "ACCOUNT_DORMANT", "MULTI_SIG_MSV_RED",
    }

    if fixture.smb_id and fixture.trigger not in _early_exit_triggers:
        # Reached the SMB section — ledger update must fire
        assert mock_ledger.called, (
            f"[{fixture.fixture_id}] SMB emit_batch_ledger_update must be called "
            f"for smb_id={fixture.smb_id!r} when workflow reaches SMB section"
        )
        if result.decision in ("STP_RETURN", "FRAUD_HOLD"):
            assert mock_notify.called, (
                f"[{fixture.fixture_id}] SMB notify_sub_member_return must be called "
                f"on STP_RETURN/FRAUD_HOLD for smb_id={fixture.smb_id!r}"
            )
    else:
        # SMB activities must NOT be called for non-SMB or early-exit scenarios
        assert not mock_ledger.called, (
            f"[{fixture.fixture_id}] emit_batch_ledger_update must NOT be called "
            f"(no smb_id or early exit at '{fixture.trigger}')"
        )

    # ── Build checklist step trace ────────────────────────────────────────────
    steps = build_inward_step_trace(fixture, result)

    # Checklist: IET watchdog must be first step
    assert steps[0]["name"] == "IET Watchdog", (
        f"[{fixture.fixture_id}] First step in trace must be IET Watchdog"
    )
    assert steps[0]["outcome"] == "SPAWNED", (
        f"[{fixture.fixture_id}] IET Watchdog outcome must be SPAWNED"
    )

    # Checklist: minimum step count sanity
    assert len(steps) >= 2, (
        f"[{fixture.fixture_id}] Step trace is too short ({len(steps)} steps)"
    )

    # ── Register in Digest ────────────────────────────────────────────────────
    register_instrument(
        instrument_id=fixture.instrument_id,
        bank_id=fixture.bank_id,
        workflow_type="INWARD",
        decision=result.decision,
        rationale=result.rationale,
        steps=steps,
        amount_range=fixture.amount_range,
        duration_ms=duration_ms,
        test_name=f"test_inward_e2e[{fixture.fixture_id}]",
    )


# ─────────────────────────────────────────────────────────────────────────────
# Suite-level sanity: fixture count matches expectations
# ─────────────────────────────────────────────────────────────────────────────

def test_fixture_counts():
    """Sanity: fixture lists must contain exactly the declared cheque counts."""
    assert OUTWARD_COUNT == 12, f"Expected 12 outward fixtures, got {OUTWARD_COUNT}"
    assert INWARD_COUNT == 20, f"Expected 20 inward fixtures, got {INWARD_COUNT}"
    assert TOTAL_CHEQUES == 32, f"Expected 32 total fixtures, got {TOTAL_CHEQUES}"


def test_fixture_ids_unique():
    """All fixture_ids must be globally unique."""
    from tests.e2e.cts.cheque_fixtures import ALL_FIXTURES
    ids = [f.fixture_id for f in ALL_FIXTURES]
    assert len(ids) == len(set(ids)), f"Duplicate fixture_ids: {[x for x in ids if ids.count(x)>1]}"


def test_fixture_languages_covered():
    """Verify multi-language coverage across both pipelines."""
    from tests.e2e.cts.cheque_fixtures import ALL_FIXTURES
    languages = {f.language for f in ALL_FIXTURES}
    required = {"English", "Hindi", "Marathi", "Tamil", "Telugu",
                "Kannada", "Gujarati", "Bengali", "Malayalam"}
    missing = required - languages
    assert not missing, f"Missing language coverage: {missing}"


def test_outward_polarity_mix():
    """Outward must have both POSITIVE and NEGATIVE scenarios."""
    polarities = {f.polarity for f in OUTWARD_FIXTURES}
    assert "POSITIVE" in polarities, "Outward must have POSITIVE scenarios"
    assert "NEGATIVE" in polarities, "Outward must have NEGATIVE scenarios"


def test_inward_polarity_mix():
    """Inward must have both POSITIVE and NEGATIVE scenarios."""
    polarities = {f.polarity for f in INWARD_FIXTURES}
    assert "POSITIVE" in polarities, "Inward must have POSITIVE scenarios"
    assert "NEGATIVE" in polarities, "Inward must have NEGATIVE scenarios"


def test_inward_outcome_variety():
    """Inward must cover all three decision outcomes."""
    outcomes = {f.expected_outcome for f in INWARD_FIXTURES}
    assert "STP_CONFIRM" in outcomes, "Inward must have STP_CONFIRM scenario"
    assert "STP_RETURN" in outcomes, "Inward must have STP_RETURN scenario"
    assert "HUMAN_REVIEW" in outcomes, "Inward must have HUMAN_REVIEW scenario"


def test_outward_outcome_variety():
    """Outward must cover all three outcome buckets."""
    outcomes = {f.expected_outcome for f in OUTWARD_FIXTURES}
    assert "ACCEPTED" in outcomes
    assert "CTS_REJECTED" in outcomes
    assert "MISMATCH_HELD" in outcomes or "POST_DATED_HELD" in outcomes
