"""
CTS Pipeline Step Registry — canonical definition of every check in the inward
and outward pipelines.

This is the single source of truth for:
  - docs/CTS_Pipeline_Checks.html  (auto-generated by modules/cts/pipeline/build.py)
  - InstrumentDigest.steps[]       (workflow accumulator populates using these step_ids)
  - Passbook UI                    (GET /v1/cts/instruments/{id}/digest reads steps[])
  - conftest.py digest report      (renders cards in registry seq order)

Adding a new pipeline check:
  1. Add a PipelineStep entry here (INWARD_STEPS or OUTWARD_STEPS)
  2. Wire the activity call + accumulator append in the workflow
  3. Run:  python -m modules.cts.pipeline.build
  Everything else (HTML, passbook, digest) updates automatically.
"""
from __future__ import annotations

from dataclasses import dataclass, field


REGISTRY_VERSION = "1.1"   # bump when steps added, removed, or reordered


@dataclass(frozen=True)
class PipelineStep:
    step_id:        str       # canonical key — used in StepResult, Immudb, passbook
    pipeline:       str       # "INWARD" | "OUTWARD"
    seq:            int       # display + sort order (1-based, gaps allowed)
    name:           str       # human-readable label for UI / digest
    technology:     str       # model / component that does the work
    source_file:    str       # relative to modules/cts/
    is_conditional: bool = False   # True = only runs when input field present
    condition_note: str  = ""      # what triggers / skips this step
    is_ai:          bool = False   # True = vLLM + Langfuse trace
    failure_outcomes: tuple[str, ...] = field(default_factory=tuple)  # e.g. ("STP_RETURN", "HUMAN_REVIEW")


# ─────────────────────────────────────────────────────────────────────────────
# INWARD PIPELINE
# Drawee bank — ChequeProcessingWorkflow (cheque_workflow.py · run())
# ─────────────────────────────────────────────────────────────────────────────

INWARD_STEPS: list[PipelineStep] = [
    PipelineStep(
        step_id="iet_watchdog",
        pipeline="INWARD",
        seq=1,
        name="IET Watchdog",
        technology="IETWatchdogWorkflow (Temporal child, ABANDON)",
        source_file="workflows/iet_watchdog_workflow.py",
        failure_outcomes=("EMERGENCY_FILE",),
    ),
    PipelineStep(
        step_id="duplicate_check",
        pipeline="INWARD",
        seq=2,
        name="Duplicate Presentment Check",
        technology="mark_leaf_presented · cheque_leaf_vault",
        source_file="workflows/activities/leaf_lifecycle.py",
        failure_outcomes=("STP_RETURN",),
    ),
    PipelineStep(
        step_id="ocr_extract",
        pipeline="INWARD",
        seq=3,
        name="OCR Extraction",
        technology="GOT-OCR2.0 + IndicOCR · cts-ocr queue",
        source_file="workflows/activities/ocr.py",
        is_ai=True,
        failure_outcomes=("HUMAN_REVIEW",),
    ),
    PipelineStep(
        step_id="kill_switch_1",
        pipeline="INWARD",
        seq=4,
        name="Kill Switch Checkpoint 1",
        technology="get_kill_switch_status · Redis",
        source_file="workflows/activities/kill_switch_lookup.py",
        failure_outcomes=("HUMAN_REVIEW",),
    ),
    PipelineStep(
        step_id="alteration_detect",
        pipeline="INWARD",
        seq=5,
        name="Alteration Detection",
        technology="Qwen2-VL 72B · cts-vision queue",
        source_file="workflows/activities/alteration.py",
        is_ai=True,
        failure_outcomes=("HUMAN_REVIEW",),
    ),
    PipelineStep(
        step_id="security_features",
        pipeline="INWARD",
        seq=6,
        name="CTS-2010 Security Features",
        technology="Qwen2-VL 72B · cts-vision queue",
        source_file="workflows/activities/security_features.py",
        is_ai=True,
        failure_outcomes=("HUMAN_REVIEW",),
    ),
    PipelineStep(
        step_id="stop_payment",
        pipeline="INWARD",
        seq=7,
        name="Stop Payment Check",
        technology="Bloom filter + CBS connector",
        source_file="workflows/activities/stop_payment.py",
        failure_outcomes=("STP_RETURN", "HUMAN_REVIEW"),
    ),
    PipelineStep(
        step_id="ifsc_validate",
        pipeline="INWARD",
        seq=8,
        name="IFSC Registry Validation",
        technology="validate_ifsc · IFSC registry",
        source_file="workflows/activities/ifsc_validator.py",
        is_conditional=True,
        condition_note="Only when ngch_ifsc provided in workflow input",
        failure_outcomes=("HUMAN_REVIEW",),
    ),
    PipelineStep(
        step_id="pps_lookup",
        pipeline="INWARD",
        seq=9,
        name="PPS Lookup",
        technology="lookup_pps · Redis PPS vault",
        source_file="workflows/activities/pps.py",
        failure_outcomes=("HUMAN_REVIEW",),
    ),
    PipelineStep(
        step_id="sig_detect",
        pipeline="INWARD",
        seq=10,
        name="Signature Presence Detection",
        technology="detect_signatures · cts-vision queue",
        source_file="workflows/activities/detect_signatures.py",
        is_ai=True,
        failure_outcomes=("HUMAN_REVIEW",),
    ),
    PipelineStep(
        step_id="sig_verify",
        pipeline="INWARD",
        seq=11,
        name="Signature Verification",
        technology="Siamese Network (PyTorch) · signature_vault",
        source_file="workflows/activities/signature.py",
        is_ai=True,
        failure_outcomes=("HUMAN_REVIEW",),
    ),
    PipelineStep(
        step_id="fraud_score",
        pipeline="INWARD",
        seq=12,
        name="Fraud Scoring",
        technology="XGBoost ensemble + SHAP",
        source_file="workflows/activities/fraud.py",
        failure_outcomes=("HUMAN_REVIEW",),
    ),
    PipelineStep(
        step_id="cheque_series",
        pipeline="INWARD",
        seq=13,
        name="Cheque Series Validation",
        technology="validate_cheque_series · Redis / CBS",
        source_file="workflows/activities/cheque_series.py",
        failure_outcomes=("STP_RETURN", "HUMAN_REVIEW"),
    ),
    PipelineStep(
        step_id="cbs_balance",
        pipeline="INWARD",
        seq=14,
        name="CBS Balance Check",
        technology="check_cbs_balance · CBS connector",
        source_file="workflows/activities/cbs.py",
        failure_outcomes=("STP_RETURN", "HUMAN_REVIEW"),
    ),
    PipelineStep(
        step_id="account_status",
        pipeline="INWARD",
        seq=15,
        name="Account Status Check",
        technology="check_account_status · CBS connector",
        source_file="workflows/activities/cbs.py",
        failure_outcomes=("STP_RETURN", "HUMAN_REVIEW"),
    ),
    PipelineStep(
        step_id="kill_switch_2",
        pipeline="INWARD",
        seq=16,
        name="Kill Switch Checkpoint 2 (Backstop)",
        technology="get_kill_switch_status · Redis",
        source_file="workflows/activities/kill_switch_lookup.py",
        failure_outcomes=("HUMAN_REVIEW",),
    ),
    PipelineStep(
        step_id="synthesise_decision",
        pipeline="INWARD",
        seq=17,
        name="Decision Synthesis",
        technology="synthesise_decision · OPA (Layer 4 Rego)",
        source_file="workflows/activities/decision.py",
        failure_outcomes=("STP_CONFIRM", "STP_RETURN", "HUMAN_REVIEW"),
    ),
    PipelineStep(
        step_id="stp_mode_routing",
        pipeline="INWARD",
        seq=18,
        name="STP Mode Routing",
        technology="config_service · stp_mode (Layer 3)",
        source_file="workflows/cheque_workflow.py",
        failure_outcomes=("HUMAN_REVIEW",),
    ),
    PipelineStep(
        step_id="persist_decision",
        pipeline="INWARD",
        seq=19,
        name="Persist Agent Decision",
        technology="persist_agent_decision · YugabyteDB",
        source_file="workflows/activities/persist_decision.py",
        failure_outcomes=(),
    ),
    PipelineStep(
        step_id="ngch_file",
        pipeline="INWARD",
        seq=20,
        name="NGCH Filing",
        technology="file_to_ngch · ngch_filer (exactly-once)",
        source_file="workflows/activities/ngch_filer.py",
        failure_outcomes=("WATCHDOG_RACE",),
    ),
    PipelineStep(
        step_id="audit_write",
        pipeline="INWARD",
        seq=21,
        name="Immudb Audit Write",
        technology="write_audit · Immudb (HSM-signed, unlimited retry)",
        source_file="workflows/activities/write_audit.py",
        failure_outcomes=(),
    ),
    PipelineStep(
        step_id="human_review_spawn",
        pipeline="INWARD",
        seq=22,
        name="HumanReviewWorkflow Spawn",
        technology="HumanReviewWorkflow (Temporal child, ABANDON)",
        source_file="workflows/human_review_workflow.py",
        is_conditional=True,
        condition_note="Only on HUMAN_REVIEW outcome",
        failure_outcomes=(),
    ),
    PipelineStep(
        step_id="smb_ledger",
        pipeline="INWARD",
        seq=23,
        name="SMB Ledger Update",
        technology="emit_batch_ledger_update + notify_sub_member_return",
        source_file="sub_member/activities.py",
        is_conditional=True,
        condition_note="Only when smb_id present in workflow input",
        failure_outcomes=(),
    ),
    PipelineStep(
        step_id="feedback_emit",
        pipeline="INWARD",
        seq=24,
        name="OCR Feedback Emit",
        technology="FeedbackEmitWorkflow (fire-and-forget, ABANDON)",
        source_file="workflows/feedback_workflow.py",
        failure_outcomes=(),
    ),
]


# ─────────────────────────────────────────────────────────────────────────────
# OUTWARD PIPELINE
# Presentee bank — OutwardScanWorkflow (outward_scan_workflow.py · _run_impl())
# ─────────────────────────────────────────────────────────────────────────────

OUTWARD_STEPS: list[PipelineStep] = [
    PipelineStep(
        step_id="ocr_extract",
        pipeline="OUTWARD",
        seq=1,
        name="OCR / CR-120 Extraction",
        technology="GOT-OCR2.0 (legacy) · Qwen2-VL (CR-120 path)",
        source_file="workflows/activities/ocr.py",
        is_ai=True,
        failure_outcomes=(),
    ),
    PipelineStep(
        step_id="date_validate",
        pipeline="OUTWARD",
        seq=2,
        name="Date Validation",
        technology="_validate_cheque_date (inline, no activity)",
        source_file="workflows/outward_scan_workflow.py",
        failure_outcomes=("POST_DATED_HELD", "CTS_REJECTED"),
    ),
    PipelineStep(
        step_id="post_dated_hold",
        pipeline="OUTWARD",
        seq=3,
        name="PostDated Hold Spawn",
        technology="PostDatedHoldWorkflow (Temporal child, ABANDON)",
        source_file="workflows/postdated_hold_workflow.py",
        is_conditional=True,
        condition_note="Only when date_validate returns POST_DATED_CHEQUE",
        failure_outcomes=(),
    ),
    PipelineStep(
        step_id="cheque_dedup",
        pipeline="OUTWARD",
        seq=4,
        name="Cheque Deduplication",
        technology="check_cheque_dedup · Redis (18-month TTL)",
        source_file="workflows/activities/outward_scan_activities.py",
        failure_outcomes=("CTS_REJECTED",),
    ),
    PipelineStep(
        step_id="rear_ocr",
        pipeline="OUTWARD",
        seq=5,
        name="Rear Image OCR",
        technology="extract_rear_payee_details · GOT-OCR2.0",
        source_file="workflows/activities/outward_scan_activities.py",
        is_conditional=True,
        is_ai=True,
        condition_note="Only when rear_image_ocr_required = true",
        failure_outcomes=(),
    ),
    PipelineStep(
        step_id="payee_validate",
        pipeline="OUTWARD",
        seq=6,
        name="Payee Account Validation",
        technology="validate_payee_account · Account Vault + CBS",
        source_file="workflows/activities/outward_scan_activities.py",
        is_conditional=True,
        condition_note="Only when payee_account_number provided",
        failure_outcomes=("CTS_REJECTED", "MISMATCH_HELD"),
    ),
    PipelineStep(
        step_id="ngch_cross_check",
        pipeline="OUTWARD",
        seq=7,
        name="NGCH Metadata Cross-Check",
        technology="cross_check_ngch_metadata",
        source_file="workflows/activities/ngch_metadata_cross_check.py",
        failure_outcomes=("CTS_REJECTED",),
    ),
    PipelineStep(
        step_id="cts2010_compliance",
        pipeline="OUTWARD",
        seq=8,
        name="CTS-2010 Compliance",
        technology="validate_cts2010 (DPI, colour depth, IQA, MICR band)",
        source_file="workflows/activities/outward_scan_activities.py",
        failure_outcomes=("CTS_REJECTED",),
    ),
    PipelineStep(
        step_id="sig_detect",
        pipeline="OUTWARD",
        seq=9,
        name="Signature Presence Detection",
        technology="detect_signatures · cts-vision queue",
        source_file="workflows/activities/detect_signatures.py",
        is_ai=True,
        failure_outcomes=("CTS_REJECTED",),
    ),
    PipelineStep(
        step_id="security_features",
        pipeline="OUTWARD",
        seq=10,
        name="CTS-2010 Security Features",
        technology="Qwen2-VL 72B · cts-vision queue",
        source_file="workflows/activities/security_features.py",
        is_ai=True,
        failure_outcomes=("CTS_REJECTED",),
    ),
    PipelineStep(
        step_id="vision_crosscheck",
        pipeline="OUTWARD",
        seq=11,
        name="Vision LLM Cross-Check",
        technology="run_vision_presentment_check · Qwen2-VL 72B",
        source_file="workflows/activities/outward_scan_activities.py",
        is_conditional=True,
        is_ai=True,
        condition_note="Only when scanner_amount_str available",
        failure_outcomes=("MISMATCH_HELD",),
    ),
    PipelineStep(
        step_id="mismatch_spawn",
        pipeline="OUTWARD",
        seq=12,
        name="MismatchResolution Spawn",
        technology="MismatchResolutionWorkflow (Temporal child, ABANDON, 4h)",
        source_file="workflows/mismatch_resolution_workflow.py",
        is_conditional=True,
        condition_note="Only on MISMATCH_HELD outcome",
        failure_outcomes=(),
    ),
    PipelineStep(
        step_id="audit_write",
        pipeline="OUTWARD",
        seq=13,
        name="Immudb Audit Write",
        technology="write_audit · Immudb (HSM-signed, unlimited retry)",
        source_file="workflows/activities/write_audit.py",
        failure_outcomes=(),
    ),
    PipelineStep(
        step_id="branch_monitor",
        pipeline="OUTWARD",
        seq=14,
        name="Branch Monitor Event",
        technology="record_outward_scan_event (best-effort)",
        source_file="workflows/activities/outward_scan_activities.py",
        failure_outcomes=(),
    ),
]


# ─────────────────────────────────────────────────────────────────────────────
# Lookups — O(1) access by step_id + pipeline
# ─────────────────────────────────────────────────────────────────────────────

_INWARD_INDEX:  dict[str, PipelineStep] = {s.step_id: s for s in INWARD_STEPS}
_OUTWARD_INDEX: dict[str, PipelineStep] = {s.step_id: s for s in OUTWARD_STEPS}


def get_step(step_id: str, pipeline: str) -> PipelineStep | None:
    """Return step definition or None if not found."""
    idx = _INWARD_INDEX if pipeline == "INWARD" else _OUTWARD_INDEX
    return idx.get(step_id)


def steps_for(pipeline: str) -> list[PipelineStep]:
    """Return ordered step list for the given pipeline."""
    return INWARD_STEPS if pipeline == "INWARD" else OUTWARD_STEPS
