"""
CSV batch summary generator for Tier 2 sub-member notifications.

PII rules:
- amount_range only — never exact rupee amount
- cheque_number_suffix (last 4) — never full cheque number
- No customer names (payee / drawer)
- instrument_id is safe to include (internal system reference)
"""
import csv
import io

from .models import SubMemberBank, SubMemberBatchLedger, SubMemberReturn


class BatchSummaryCSVGenerator:
    """
    Generates CSV string for attachment in Tier 2 batch summary email.
    Output is a self-contained CSV with a header block, data rows, and summary footer.
    """

    COLUMNS = [
        "instrument_id",
        "cheque_ref_last4",
        "return_reason",
        "clearing_bucket",
        "amount_range",
        "returned_at",
    ]

    def generate(
        self,
        sub_member: SubMemberBank,
        ledger: SubMemberBatchLedger,
        returns: list[SubMemberReturn],
    ) -> str:
        buf = io.StringIO()

        # Metadata header block (comment lines)
        buf.write(f"# ASTRA CTS — Sub-Member Batch Return Summary\n")
        buf.write(f"# Bank: {sub_member.bank_name}\n")
        buf.write(f"# Sub-Member ID: {sub_member.sub_member_id}\n")
        buf.write(f"# Session: {ledger.clearing_session} {ledger.session_date}\n")
        buf.write(f"# Generated by: ASTRA CTS Notification Service\n")
        buf.write(f"# Note: Amounts shown as range buckets only per RBI data handling guidelines\n")
        buf.write("#\n")

        writer = csv.DictWriter(buf, fieldnames=self.COLUMNS)
        writer.writeheader()
        for row in self.generate_rows(returns):
            writer.writerow(row)

        buf.write("#\n")
        buf.write(self.generate_footer_summary(ledger))

        return buf.getvalue()

    def generate_rows(self, returns: list[SubMemberReturn]) -> list[dict]:
        rows = []
        for r in returns:
            rows.append({
                "instrument_id": r.instrument_id,
                "cheque_ref_last4": f"****{r.cheque_number_suffix}",
                "return_reason": r.return_reason,
                "clearing_bucket": r.bucket.value,
                "amount_range": r.amount_range,
                "returned_at": r.returned_at.strftime("%Y-%m-%d %H:%M:%S"),
            })
        return rows

    def generate_footer_summary(self, ledger: SubMemberBatchLedger) -> str:
        return_pct = ledger.return_rate * 100
        stp_pct = ledger.stp_rate * 100
        lines = [
            "# --- SESSION SUMMARY ---",
            f"# Total Received : {ledger.total_received}",
            f"# STP Pass       : {ledger.stp_pass} ({stp_pct:.2f}%)",
            f"# STP Return     : {ledger.stp_return} ({return_pct:.2f}%)",
            f"# Eyeball Queue  : {ledger.eyeball}",
            f"# Fraud Hold     : {ledger.fraud_hold}",
            f"# IET Emergency  : {ledger.iet_emergency}",
            f"# Soft Hold      : {'YES' if ledger.soft_hold_active else 'NO'}",
        ]
        return "\n".join(lines) + "\n"
