"""
ASTRA Pilot Init Script
=======================
Run ONCE before first launch of main.py on a new machine or after wiping the DB.

What it does:
  1. Generates a persistent RS256 keypair (written to secrets/ — gitignored)
  2. Writes scripts/.env.dev with all ASTRA_SECRET_* and platform env vars
     pointing at the docker-compose dev stack (ports defined in docker-compose.dev.yml)
  3. Connects to YugabyteDB and applies the schema DDL (idempotent — safe to re-run)
  4. Seeds 3 default user accounts into platform.local_auth_accounts

Usage:
  cd bank-intelligence-platform
  python scripts/dev-init.py [--bank-id saraswat-coop]

After this runs, start the API:
  source scripts/.env.dev && uvicorn apps.api.main:app --host 0.0.0.0 --port 8010 --reload

Start the CTS worker (separate terminal):
  source scripts/.env.dev && python -m modules.cts.worker

Seeded accounts (initial passwords — change after first login):
  admin    / Admin@Astra2026!  (bank_it_admin)
  ops      / Ops@Astra2026!   (ops_manager)
  reviewer / Rev@Astra2026!   (ops_reviewer)
"""

import argparse
import asyncio
import os
import sys
from pathlib import Path

# Make sure we run from repo root
REPO_ROOT = Path(__file__).parent.parent
os.chdir(REPO_ROOT)
sys.path.insert(0, str(REPO_ROOT))


def generate_rs256_keypair():
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa

    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    priv_pem = private_key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    ).decode()
    pub_pem = private_key.public_key().public_bytes(
        serialization.Encoding.PEM,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode()
    return priv_pem, pub_pem


def write_env_file(bank_id: str, priv_pem: str, pub_pem: str):
    # Escape newlines inside PEM for shell export
    priv_escaped = priv_pem.replace("\n", "\\n")
    pub_escaped = pub_pem.replace("\n", "\\n")

    env_content = f"""# ASTRA Dev Pilot Environment — generated by scripts/dev-init.py
# Source this before starting main.py:
#   source scripts/.env.dev
# DO NOT commit this file — it is gitignored (contains private key).

# ── Identity ──────────────────────────────────────────────────────────────────
export BANK_ID={bank_id}
export ASTRA_ENV=development
export ASTRA_SECRETS_BACKEND=env

# ── Platform env vars (get_platform() reads these directly as env vars) ───────
export ENV=development
export MINIO_ENDPOINT=localhost:19000
export MINIO_SECURE=false

# ── Secrets (ASTRA_SECRET_* → config_service.get_secret()) ───────────────────

# Config service internal connections (Layer 3 DB + Redis cache)
export ASTRA_SECRET_REDIS_CONFIG_URL="redis://localhost:16379/1"
export ASTRA_SECRET_DB_CONFIG_DSN="postgresql://yugabyte:yugabyte@localhost:15433/yugabyte"

# Session signing keys (RS256 — generated once by dev-init.py, persistent)
export ASTRA_SECRET_AUTH_SESSION_PRIVATE_KEY="{priv_escaped}"
export ASTRA_SECRET_AUTH_SESSION_PUBLIC_KEY="{pub_escaped}"

# Redis clusters
export ASTRA_SECRET_REDIS_CTS_URL="redis://localhost:16379/0"
export ASTRA_SECRET_REDIS_EJ_URL="redis://localhost:16380/0"

# YugabyteDB
export ASTRA_SECRET_DB_CTS_DSN="postgresql://yugabyte:yugabyte@localhost:15433/yugabyte"

# Kafka (KRaft mode, advertised on host port 19092)
export ASTRA_SECRET_KAFKA_BOOTSTRAP_SERVERS="localhost:19092"

# MinIO
export ASTRA_SECRET_MINIO_ACCESS_KEY="astra-dev"
export ASTRA_SECRET_MINIO_SECRET_KEY="astra-dev-secret"

# Temporal
export ASTRA_SECRET_TEMPORAL_HOST="localhost:17233"

# PII hash pepper (bank-specific — generated per bank; change before production)
export ASTRA_SECRET_BANKS_{bank_id.upper().replace('-', '_')}_PII_HASH_PEPPER="dev-pepper-change-before-prod-{bank_id}"

# CBS connector (leave blank — CBS wiring is deferred for pilot)
export ASTRA_SECRET_CBS_FINACLE_PASSWORD=""
export ASTRA_SECRET_CBS_BANCS_PASSWORD=""
export ASTRA_SECRET_CBS_FLEXCUBE_PASSWORD=""

# NGCH (deferred — pilot does not submit to live NGCH)
export ASTRA_SECRET_NGCH_API_KEY="pilot-placeholder"
export ASTRA_SECRET_NGCH_SFTP_PRIVATE_KEY=""
"""
    env_path = REPO_ROOT / "scripts" / ".env.dev"
    env_path.write_text(env_content, encoding="utf-8")
    print(f"  ✓ Wrote {env_path}")


async def apply_schema(bank_id: str):
    import asyncpg

    # Import the canonical DDL from dev_auth_server (single source of truth for dev schema)
    sys.path.insert(0, str(REPO_ROOT))
    from apps.api.dev_auth_server import _DEV_SCHEMA_DDL

    dsn = "postgresql://yugabyte:yugabyte@localhost:15433/yugabyte"
    print(f"  Connecting to YugabyteDB at localhost:15433 ...")
    pool = await asyncpg.create_pool(dsn=dsn, min_size=1, max_size=3, command_timeout=30)
    async with pool.acquire() as conn:
        await conn.execute(_DEV_SCHEMA_DDL)
    await pool.close()
    print("  ✓ Schema applied (all tables created/verified)")
    return pool


async def seed_users(bank_id: str):
    import asyncpg
    import argon2

    ph = argon2.PasswordHasher()

    users = [
        {
            "user_id": f"usr-admin-{bank_id}",
            "bank_id": bank_id,
            "entity_type": "SB",
            "entity_id": bank_id,
            "username": "admin",
            "display_name": "Bank IT Admin",
            "password_hash": ph.hash("Admin@Astra2026!"),
            "role": "bank_it_admin",
            "permission_level": "ADMIN",
            "bank_type": "SB",
            "clearing_zones": [],
            "email": f"admin@{bank_id}.internal",
            "is_active": True,
        },
        {
            "user_id": f"usr-ops-{bank_id}",
            "bank_id": bank_id,
            "entity_type": "SB",
            "entity_id": bank_id,
            "username": "ops",
            "display_name": "Ops Manager",
            "password_hash": ph.hash("Ops@Astra2026!"),
            "role": "ops_manager",
            "permission_level": "EDIT",
            "bank_type": "SB",
            "clearing_zones": [],
            "email": f"ops@{bank_id}.internal",
            "is_active": True,
        },
        {
            "user_id": f"usr-reviewer-{bank_id}",
            "bank_id": bank_id,
            "entity_type": "SB",
            "entity_id": bank_id,
            "username": "reviewer",
            "display_name": "Ops Reviewer",
            "password_hash": ph.hash("Rev@Astra2026!"),
            "role": "ops_reviewer",
            "permission_level": "EDIT",
            "bank_type": "SB",
            "clearing_zones": ["MUMBAI", "PUNE"],
            "email": f"reviewer@{bank_id}.internal",
            "is_active": True,
        },
    ]

    dsn = "postgresql://yugabyte:yugabyte@localhost:15433/yugabyte"
    pool = await asyncpg.create_pool(dsn=dsn, min_size=1, max_size=3, command_timeout=30)
    async with pool.acquire() as conn:
        for u in users:
            await conn.execute(
                """
                INSERT INTO platform.local_auth_accounts
                (user_id, bank_id, entity_type, entity_id, username, display_name,
                 password_hash, role, permission_level, bank_type, clearing_zones,
                 email, is_active)
                VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
                ON CONFLICT (user_id) DO UPDATE SET
                  display_name=EXCLUDED.display_name,
                  role=EXCLUDED.role,
                  permission_level=EXCLUDED.permission_level,
                  email=EXCLUDED.email,
                  is_active=EXCLUDED.is_active
                """,
                u["user_id"], u["bank_id"], u["entity_type"], u["entity_id"],
                u["username"], u["display_name"], u["password_hash"],
                u["role"], u["permission_level"], u["bank_type"],
                u["clearing_zones"], u["email"], u["is_active"],
            )
    await pool.close()
    print("  ✓ Seeded 3 default users: admin / ops / reviewer")


async def main():
    parser = argparse.ArgumentParser(description="ASTRA Pilot Init")
    parser.add_argument("--bank-id", default="saraswat-coop", help="Bank ID to initialise")
    args = parser.parse_args()
    bank_id = args.bank_id

    print(f"\nASTRA Pilot Init — bank_id={bank_id}")
    print("=" * 52)

    print("\n[1/4] Generating RS256 session keypair ...")
    priv_pem, pub_pem = generate_rs256_keypair()
    print("  ✓ RS256 keypair generated (2048-bit)")

    print("\n[2/4] Writing scripts/.env.dev ...")
    write_env_file(bank_id, priv_pem, pub_pem)

    print("\n[3/4] Applying DB schema to YugabyteDB ...")
    try:
        await apply_schema(bank_id)
    except Exception as e:
        print(f"  ✗ DB schema failed: {e}")
        print("    Is docker-compose running? Start it first:")
        print("    docker compose -f infra/docker-compose.dev.yml up -d")
        sys.exit(1)

    print("\n[4/4] Seeding default users ...")
    try:
        await seed_users(bank_id)
    except Exception as e:
        print(f"  ✗ User seeding failed: {e}")
        print(f"    Error: {e}")
        sys.exit(1)

    print(f"""
✓ Init complete.

Next steps:
  1. source scripts/.env.dev
  2. uvicorn apps.api.main:app --host 0.0.0.0 --port 8010 --reload

Default credentials (change after first login):
  admin    / Admin@Astra2026!   (bank_it_admin)
  ops      / Ops@Astra2026!    (ops_manager)
  reviewer / Rev@Astra2026!    (ops_reviewer)
""")


if __name__ == "__main__":
    asyncio.run(main())
