"""
ASTRA Pilot Init Script
=======================
Run ONCE on a new machine or after wiping the database.

What it does:
  1. Generates a persistent RS256 keypair → secrets/session.priv.pem + session.pub.pem
  2. Writes scripts/.env.ps1  (Windows PowerShell loader)
     and   scripts/.env.dev   (Linux/Mac bash loader)
  3. Applies the DB schema to YugabyteDB (idempotent — safe to re-run)
  4. Seeds 3 default operator accounts

Usage:
  python scripts/dev-init.py [--bank-id saraswat-coop]
"""

import argparse
import asyncio
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.resolve()
os.chdir(REPO_ROOT)
sys.path.insert(0, str(REPO_ROOT))

SECRETS_DIR = REPO_ROOT / "secrets"
ENV_PS1     = REPO_ROOT / "scripts" / ".env.ps1"
ENV_DEV     = REPO_ROOT / "scripts" / ".env.dev"


# ── 1. RS256 keypair ──────────────────────────────────────────────────────────

def generate_rs256_keypair():
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa

    priv = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    priv_pem = priv.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    ).decode()
    pub_pem = priv.public_key().public_bytes(
        serialization.Encoding.PEM,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode()
    return priv_pem, pub_pem


def write_keypair(priv_pem: str, pub_pem: str):
    SECRETS_DIR.mkdir(exist_ok=True)
    (SECRETS_DIR / "session.priv.pem").write_text(priv_pem, encoding="utf-8")
    (SECRETS_DIR / "session.pub.pem").write_text(pub_pem,  encoding="utf-8")
    print("  ✓ Keys written to secrets/session.priv.pem + session.pub.pem")


# ── 2. Env files ─────────────────────────────────────────────────────────────

def write_env_ps1(bank_id: str):
    """PowerShell env loader — reads PEM from files at source time."""
    pepper = f"dev-pepper-change-before-prod-{bank_id}"
    content = f"""# ASTRA Dev Pilot — PowerShell environment loader
# Generated by scripts/dev-init.py — DO NOT COMMIT (gitignored)
# Usage: . scripts\\.env.ps1   (dot-source in every terminal before starting a service)

$RepoRoot = "$PSScriptRoot\\.."

# Identity
$env:BANK_ID                    = "{bank_id}"
$env:ASTRA_ENV                  = "development"
$env:ASTRA_SECRETS_BACKEND      = "env"

# Platform env vars (config_service.get_platform reads these directly)
$env:ENV                        = "development"
$env:MINIO_ENDPOINT             = "localhost:19000"
$env:MINIO_SECURE               = "false"

# Config-service internal connections
$env:ASTRA_SECRET_REDIS_CONFIG_URL  = "redis://localhost:16379/1"
$env:ASTRA_SECRET_DB_CONFIG_DSN     = "postgresql://yugabyte:yugabyte@localhost:15433/yugabyte"

# Session signing keys — read from PEM files (avoids multiline escaping issues)
$env:ASTRA_SECRET_AUTH_SESSION_PRIVATE_KEY = (Get-Content "$RepoRoot\\secrets\\session.priv.pem" -Raw)
$env:ASTRA_SECRET_AUTH_SESSION_PUBLIC_KEY  = (Get-Content "$RepoRoot\\secrets\\session.pub.pem"  -Raw)

# Redis clusters
$env:ASTRA_SECRET_REDIS_CTS_URL  = "redis://localhost:16379/0"
$env:ASTRA_SECRET_REDIS_EJ_URL   = "redis://localhost:16380/0"

# YugabyteDB
$env:ASTRA_SECRET_DB_CTS_DSN     = "postgresql://yugabyte:yugabyte@localhost:15433/yugabyte"

# Kafka
$env:ASTRA_SECRET_KAFKA_BOOTSTRAP_SERVERS = "localhost:19092"

# MinIO
$env:ASTRA_SECRET_MINIO_ACCESS_KEY  = "astra-dev"
$env:ASTRA_SECRET_MINIO_SECRET_KEY  = "astra-dev-secret"

# Temporal
$env:ASTRA_SECRET_TEMPORAL_HOST  = "localhost:17233"

# ImmuDB
$env:ASTRA_SECRET_IMMUDB_ADMIN_PASSWORD = "astra-dev-immudb"

# PII hash pepper (change before handling real customer data)
$env:ASTRA_SECRET_BANKS_{bank_id.upper().replace('-', '_')}_PII_HASH_PEPPER = "{pepper}"

# NGCH — pilot placeholder (no live NGCH filing in POC)
$env:ASTRA_SECRET_NGCH_API_KEY         = "pilot-placeholder"
$env:ASTRA_SECRET_NGCH_SFTP_PRIVATE_KEY = ""

# CBS connectors — blank until CBS wiring is implemented
$env:ASTRA_SECRET_CBS_FINACLE_PASSWORD  = ""
$env:ASTRA_SECRET_CBS_BANCS_PASSWORD    = ""
$env:ASTRA_SECRET_CBS_FLEXCUBE_PASSWORD = ""

Write-Host "[env] ASTRA environment loaded (BANK_ID=$env:BANK_ID, ENV=$env:ASTRA_ENV)" -ForegroundColor DarkGray
"""
    ENV_PS1.write_text(content, encoding="utf-8")
    print(f"  ✓ Wrote scripts/.env.ps1")


def write_env_dev(bank_id: str):
    """Bash env loader — reads PEM from files at source time."""
    pepper = f"dev-pepper-change-before-prod-{bank_id}"
    content = f"""# ASTRA Dev Pilot — Bash environment loader
# Generated by scripts/dev-init.py — DO NOT COMMIT (gitignored)
# Usage: source scripts/.env.dev

_REPO="$(cd "$(dirname "${{BASH_SOURCE[0]}}")/.." && pwd)"

export BANK_ID="{bank_id}"
export ASTRA_ENV="development"
export ASTRA_SECRETS_BACKEND="env"
export ENV="development"
export MINIO_ENDPOINT="localhost:19000"
export MINIO_SECURE="false"

# Platform Layer 1/2 config — read by config_service.get_platform()
export TEMPORAL_ADDRESS="localhost:17233"
export TEMPORAL_NAMESPACE="default"
export KAFKA_BOOTSTRAP_SERVERS="localhost:19092"
export OPA_REQUIRED="false"

export ASTRA_SECRET_REDIS_CONFIG_URL="redis://localhost:16379/1"
export ASTRA_SECRET_DB_CONFIG_DSN="postgresql://yugabyte:yugabyte@localhost:15433/yugabyte"

export ASTRA_SECRET_AUTH_SESSION_PRIVATE_KEY="$(cat "$_REPO/secrets/session.priv.pem")"
export ASTRA_SECRET_AUTH_SESSION_PUBLIC_KEY="$(cat "$_REPO/secrets/session.pub.pem")"

export ASTRA_SECRET_REDIS_CTS_URL="redis://localhost:16379/0"
export ASTRA_SECRET_REDIS_EJ_URL="redis://localhost:16380/0"
export ASTRA_SECRET_DB_CTS_DSN="postgresql://yugabyte:yugabyte@localhost:15433/yugabyte"
export ASTRA_SECRET_KAFKA_BOOTSTRAP_SERVERS="localhost:19092"
export ASTRA_SECRET_MINIO_ACCESS_KEY="astra-dev"
export ASTRA_SECRET_MINIO_SECRET_KEY="astra-dev-secret"
export ASTRA_SECRET_TEMPORAL_HOST="localhost:17233"
export ASTRA_SECRET_IMMUDB_ADMIN_PASSWORD="astra-dev-immudb"
export ASTRA_SECRET_BANKS_{bank_id.upper().replace('-', '_')}_PII_HASH_PEPPER="{pepper}"
export ASTRA_SECRET_NGCH_API_KEY="pilot-placeholder"
export ASTRA_SECRET_NGCH_SFTP_PRIVATE_KEY=""
export ASTRA_SECRET_CBS_FINACLE_PASSWORD=""
export ASTRA_SECRET_CBS_BANCS_PASSWORD=""
export ASTRA_SECRET_CBS_FLEXCUBE_PASSWORD=""

echo "[env] ASTRA environment loaded (BANK_ID=$BANK_ID)"
"""
    ENV_DEV.write_text(content, encoding="utf-8")
    print(f"  ✓ Wrote scripts/.env.dev")


# ── 3. DB schema ──────────────────────────────────────────────────────────────

async def apply_schema():
    import asyncpg
    from apps.api.dev_auth_server import _DEV_SCHEMA_DDL

    pool = await asyncpg.create_pool(
        dsn="postgresql://yugabyte:yugabyte@localhost:15433/yugabyte",
        min_size=1, max_size=3, command_timeout=30,
    )
    async with pool.acquire() as conn:
        await conn.execute(_DEV_SCHEMA_DDL)
    await pool.close()
    print("  ✓ Schema applied — all tables created/verified")


# ── 4. Seed users ─────────────────────────────────────────────────────────────

async def seed_users(bank_id: str):
    import asyncpg
    from argon2 import PasswordHasher

    ph = PasswordHasher()
    users = [
        ("admin",    "Bank IT Admin",   ph.hash("Admin@Astra2026!"),  "bank_it_admin",  "ADMIN", "SB", []),
        ("ops",      "Ops Manager",     ph.hash("Ops@Astra2026!"),    "ops_manager",    "EDIT",  "SB", []),
        ("reviewer", "Ops Reviewer",    ph.hash("Rev@Astra2026!"),    "ops_reviewer",   "EDIT",  "SB", ["MUMBAI", "PUNE"]),
    ]
    pool = await asyncpg.create_pool(
        dsn="postgresql://yugabyte:yugabyte@localhost:15433/yugabyte",
        min_size=1, max_size=3, command_timeout=30,
    )
    async with pool.acquire() as conn:
        for username, display, pwd_hash, role, perm, btype, zones in users:
            await conn.execute(
                """
                INSERT INTO platform.local_auth_accounts
                  (user_id, bank_id, entity_type, entity_id, username, display_name,
                   password_hash, role, permission_level, bank_type, clearing_zones,
                   email, is_active)
                VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
                ON CONFLICT (user_id) DO UPDATE SET
                  entity_type=EXCLUDED.entity_type,
                  display_name=EXCLUDED.display_name,
                  role=EXCLUDED.role,
                  permission_level=EXCLUDED.permission_level,
                  is_active=EXCLUDED.is_active
                """,
                f"usr-{username}-{bank_id}", bank_id, "sb", bank_id,
                username, display, pwd_hash, role, perm, btype,
                zones, f"{username}@{bank_id}.internal", True,
            )
    await pool.close()
    print("  ✓ Seeded users: admin / ops / reviewer")


# ── Main ──────────────────────────────────────────────────────────────────────

async def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--bank-id", default="saraswat-coop")
    args = parser.parse_args()
    bank_id = args.bank_id

    print(f"\n{'='*56}")
    print(f"  ASTRA Pilot Init  —  bank_id: {bank_id}")
    print(f"{'='*56}\n")

    print("[1/4] Generating RS256 session keypair ...")
    priv_pem, pub_pem = generate_rs256_keypair()
    write_keypair(priv_pem, pub_pem)

    print("\n[2/4] Writing environment files ...")
    write_env_ps1(bank_id)
    write_env_dev(bank_id)

    print("\n[3/4] Applying DB schema ...")
    try:
        await apply_schema()
    except Exception as e:
        print(f"\n  ✗ DB connection failed: {e}")
        print("  → Make sure docker-compose is running:")
        print("    docker compose -f infra/docker-compose.dev.yml up -d")
        print("  → Then re-run this script.")
        sys.exit(1)

    print("\n[4/4] Seeding default users ...")
    try:
        await seed_users(bank_id)
    except Exception as e:
        print(f"  ✗ Seeding failed: {e}")
        sys.exit(1)

    print(f"""
{'='*56}
  Init complete ✓
{'='*56}

  Default credentials (change after first login):
    admin     / Admin@Astra2026!   (bank_it_admin)
    ops       / Ops@Astra2026!    (ops_manager)
    reviewer  / Rev@Astra2026!    (ops_reviewer)

  To start everything: run  scripts\\start.ps1
{'='*56}
""")


if __name__ == "__main__":
    asyncio.run(main())
