; ASTRA CTS Scanner Agent — Windows Installer
; Built with NSIS 3.x (makensis)
;
; Security model — why branch_id cannot be forged:
;   The installer does NOT ask the IT admin to enter a branch ID.
;   Instead, the admin enters a one-time registration code (8 chars) that was
;   generated by ops_manager in the ASTRA Admin UI for a specific branch.
;   The installer exchanges the code for the full branch config via
;   POST /v1/cts/admin/scanner/register — the server returns branch_id, bank_id,
;   bank_ifsc, and a machine-bound API token. The code is single-use and deleted
;   on the server immediately after exchange.
;
;   Result: IT admin at Agra branch physically cannot claim Lucknow's branch_id —
;   they don't know Lucknow's registration code, and even if they guessed it,
;   it would have already been used and deleted.
;
; What this installer does:
;   1. IT admin enters: ASTRA Server URL + 8-char registration code
;   2. Calls POST /v1/cts/admin/scanner/register → receives full config
;   3. Writes config.ini (non-secret: branch_id, bank_id, bank_ifsc, scanner settings)
;   4. Writes token.dat with restricted NTFS ACL (SYSTEM + Administrators only)
;   5. Copies astra-cts-scanner.exe + Canon DLLs to install directory
;   6. Installs and starts the Windows service (ASTRAScannerAgent)
;
; Build on CI (Linux GitLab runner with NSIS + plugins):
;   makensis -DVERSION=1.4.2 astra-scanner-setup.nsi
;
; Required NSIS plugins (place in /usr/share/nsis/Plugins/x86-unicode/ on CI):
;   Inetc        — https://nsis.sourceforge.io/Inetc_plug-in
;   SimpleSC     — https://nsis.sourceforge.io/NSIS_Simple_Service_Plugin
;   AccessControl — https://nsis.sourceforge.io/AccessControl_plug-in
;   nsJSON       — https://nsis.sourceforge.io/NsJSON_plug-in
;
; Canon DLL note:
;   Place the following Canon SDK files alongside this .nsi before building.
;   They are NOT in git (OEM license) — CI fetches them from the protected
;   ASTRA artifact registry using ASTRA_ARTIFACT_TOKEN + CANON_DLL_STORE_URL.
;     Canon\CanoCheetah.dll
;     Canon\CanoCheetahRanger.dll
;     Canon\CeiIQA.ini

Unicode True

!define APPNAME   "ASTRA CTS Scanner Agent"
!define APPID     "ASTRAScannerAgent"
!define PUBLISHER "ASTRA — 9va4 Technologies Pvt Ltd"
!define INSTALL_DIR "$PROGRAMFILES64\ASTRA\ScannerAgent"
!define REG_ROOT  "HKLM"
!define REG_KEY   "Software\ASTRA\ScannerAgent"
!define REG_UNINST "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPID}"

!ifndef VERSION
  !define VERSION "dev"
!endif

!include "MUI2.nsh"
!include "nsDialogs.nsh"
!include "LogicLib.nsh"
!include "FileFunc.nsh"

Name          "${APPNAME} ${VERSION}"
OutFile       "ASTRA-Scanner-Setup-${VERSION}.exe"
InstallDir    "${INSTALL_DIR}"
InstallDirRegKey ${REG_ROOT} "${REG_KEY}" "InstallDir"
RequestExecutionLevel admin
SetCompressor /SOLID lzma
BrandingText  "${PUBLISHER}"

; ── Variables ────────────────────────────────────────────────────────────────
; Page 1 — inputs from IT admin (only 2 fields)
Var ASTRAApiUrl
Var RegistrationCode

; Page 2 — scanner hardware (local, not server-side)
Var EnableImprinter
Var EndorsementText
Var EnableUVScan

; Populated by the server after code exchange (never entered by user)
Var BankID
Var BankIFSC
Var BranchID
Var BranchName
Var ApiToken
Var ServerEndorsementText
Var ServerEnableImprinter
Var ServerEnableUVScan
Var ServerMOCRWeight

; Dialog handles
Var hDlg
Var hApiUrl
Var hRegCode
Var hVerifyBtn
Var hVerifyStatus
Var hImprinterChk
Var hEndorsementText
Var hUVScanChk

; ── MUI Pages ────────────────────────────────────────────────────────────────
!define MUI_ABORTWARNING

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "..\assets\license.rtf"
Page custom RegistrationPage  RegistrationPageLeave
Page custom ScannerHardwarePage ScannerHardwarePageLeave
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

; ═══════════════════════════════════════════════════════════════════════════
; PAGE 1 — Registration
; Only two inputs: ASTRA Server URL + 8-char one-time code.
; The "Verify & Continue" button calls the register API and populates all
; branch fields from the server response — user never types branch identity.
; ═══════════════════════════════════════════════════════════════════════════
Function RegistrationPage
  nsDialogs::Create 1018
  Pop $hDlg
  ${If} $hDlg == error
    Abort
  ${EndIf}

  ${NSD_CreateLabel} 0 0 100% 16u "Branch Registration"
  Pop $0
  CreateFont $1 "Segoe UI" 10 700
  SendMessage $0 ${WM_SETFONT} $1 1

  ${NSD_CreateLabel} 0 22u 100% 18u \
    "Enter the ASTRA Server URL and the one-time registration code generated \
for this branch in ASTRA Admin UI → Branches → Register Scanner."
  Pop $0

  ${NSD_CreateLabel} 0 46u 100% 10u "ASTRA Server URL"
  Pop $0
  ${NSD_CreateText} 0 58u 100% 14u "https://api.astra.yourbank.internal"
  Pop $hApiUrl

  ${NSD_CreateLabel} 0 78u 100% 10u "Registration Code  (8 characters, from Admin UI)"
  Pop $0
  ${NSD_CreateText} 0 90u 40% 14u ""
  Pop $hRegCode
  ; Uppercase-only hint
  SendMessage $hRegCode ${EM_LIMITTEXT} 8 0

  ${NSD_CreateButton} 44% 89u 20% 16u "Verify →"
  Pop $hVerifyBtn
  ${NSD_OnClick} $hVerifyBtn VerifyRegistrationCode

  ; Status label — updated by VerifyRegistrationCode
  ${NSD_CreateLabel} 0 110u 100% 40u ""
  Pop $hVerifyStatus

  ; Pre-fill API URL from previous install if upgrading
  ReadRegStr $0 ${REG_ROOT} "${REG_KEY}" "ApiUrl"
  ${If} $0 != ""
    ${NSD_SetText} $hApiUrl $0
  ${EndIf}

  nsDialogs::Show
FunctionEnd

; Called when IT admin clicks "Verify →"
; POSTs {registration_code, machine_id} to /v1/cts/admin/scanner/register.
; On success: populates all Var fields from JSON response.
; On failure: shows error in the status label.
Function VerifyRegistrationCode
  ${NSD_GetText} $hApiUrl    $ASTRAApiUrl
  ${NSD_GetText} $hRegCode   $RegistrationCode

  ${NSD_SetText} $hVerifyStatus "Contacting ASTRA server..."

  ${If} $ASTRAApiUrl == ""
    ${NSD_SetText} $hVerifyStatus "ERROR: Enter the ASTRA Server URL first."
    Return
  ${EndIf}
  ${If} $RegistrationCode == ""
    ${NSD_SetText} $hVerifyStatus "ERROR: Enter the 8-character registration code."
    Return
  ${EndIf}

  ; Get Windows machine name for token binding
  ReadEnvStr $0 "COMPUTERNAME"
  StrCpy $1 $0   ; machine_id = COMPUTERNAME

  ; Build JSON request body
  StrCpy $2 '{"registration_code":"$RegistrationCode","machine_id":"$1"}'

  ; POST to /v1/cts/admin/scanner/register
  StrCpy $3 "$TEMP\astra_reg_response.json"
  Inetc::post \
    /CAPTION "Verifying registration code..." \
    /HEADER "Content-Type: application/json" \
    "$ASTRAApiUrl/v1/cts/admin/scanner/register" \
    $2 \
    "$3" /END
  Pop $4   ; HTTP status or error string

  ${If} $4 != "OK"
    ${NSD_SetText} $hVerifyStatus \
      "ERROR: Could not reach server ($4).$\r$\nCheck the Server URL and network."
    Return
  ${EndIf}

  ; Check HTTP response code — Inetc returns "OK" for any 2xx, or "Cancelled" etc.
  ; Read the response file and parse key fields.
  ; nsJSON plugin parses the response into accessible variables.
  nsJSON::Set /tree
  FileOpen $5 "$3" r
  FileRead  $5 $6
  FileClose $5

  ; Check for error_code field (server returned 4xx/5xx)
  nsJSON::Get /tree /key "error_code" /end
  Pop $7
  ${If} $7 != ""
    nsJSON::Get /tree /key "message" /end
    Pop $8
    ${NSD_SetText} $hVerifyStatus "ERROR: $8"
    Return
  ${EndIf}

  ; Extract all fields from the response
  nsJSON::Get /tree /key "branch_id"          /end  Pop $BranchID
  nsJSON::Get /tree /key "branch_name"        /end  Pop $BranchName
  nsJSON::Get /tree /key "bank_id"            /end  Pop $BankID
  nsJSON::Get /tree /key "bank_ifsc"          /end  Pop $BankIFSC
  nsJSON::Get /tree /key "api_token"          /end  Pop $ApiToken
  nsJSON::Get /tree /key "endorsement_text"   /end  Pop $ServerEndorsementText
  nsJSON::Get /tree /key "enable_imprinter"   /end  Pop $ServerEnableImprinter
  nsJSON::Get /tree /key "enable_uv_scan"     /end  Pop $ServerEnableUVScan
  nsJSON::Get /tree /key "mocr_weight"        /end  Pop $ServerMOCRWeight

  ${If} $BranchID == ""
    ${NSD_SetText} $hVerifyStatus \
      "ERROR: Server returned empty branch_id. Contact your ASTRA administrator."
    Return
  ${EndIf}

  ; Success — show confirmed branch identity to IT admin (read-only confirmation)
  ${NSD_SetText} $hVerifyStatus \
    "✓  Verified.$\r$\nBranch: $BranchName  ($BranchID)$\r$\nBank: $BankID | IFSC: $BankIFSC$\r$\nClick Next to continue."
FunctionEnd

Function RegistrationPageLeave
  ; Prevent Next if verification hasn't succeeded
  ${If} $BranchID == ""
    MessageBox MB_OK|MB_ICONEXCLAMATION \
      "Click 'Verify →' first and confirm the branch details before continuing."
    Abort
  ${EndIf}
  ${If} $ApiToken == ""
    MessageBox MB_OK|MB_ICONEXCLAMATION \
      "No API token received. Click 'Verify →' again."
    Abort
  ${EndIf}
FunctionEnd

; ═══════════════════════════════════════════════════════════════════════════
; PAGE 2 — Scanner Hardware
; These settings are local to the hardware at this branch, not returned
; by the server. Server provides defaults (endorsement_text etc.) which
; pre-fill the fields; IT admin can override for local hardware differences.
; ═══════════════════════════════════════════════════════════════════════════
Function ScannerHardwarePage
  nsDialogs::Create 1018
  Pop $hDlg
  ${If} $hDlg == error
    Abort
  ${EndIf}

  ${NSD_CreateLabel} 0 0 100% 16u "Scanner Hardware — $BranchName"
  Pop $0
  CreateFont $1 "Segoe UI" 10 700
  SendMessage $0 ${WM_SETFONT} $1 1

  ${NSD_CreateLabel} 0 20u 100% 10u "Endorsement text  (printed on back of each cheque)"
  Pop $0
  ${NSD_CreateText} 0 32u 100% 14u ""
  Pop $hEndorsementText
  ; Pre-fill with server-provided default
  ${NSD_SetText} $hEndorsementText $ServerEndorsementText

  ${NSD_CreateCheckBox} 0 52u 100% 12u "Endorsement imprinter hardware present and licensed"
  Pop $hImprinterChk
  ${If} $ServerEnableImprinter == "true"
    ${NSD_SetState} $hImprinterChk ${BST_CHECKED}
  ${EndIf}

  ${NSD_CreateCheckBox} 0 68u 100% 12u "UV scanner unit fitted (Canon CR-120 UV model only)"
  Pop $hUVScanChk
  ${If} $ServerEnableUVScan == "true"
    ${NSD_SetState} $hUVScanChk ${BST_CHECKED}
  ${EndIf}

  ${NSD_CreateLabel} 0 88u 100% 30u \
    "Scanner discovery is automatic via USB.$\r$\n\
     Ensure the Canon CR-120/150 driver is installed and the scanner is connected \
     before clicking Install."
  Pop $0

  nsDialogs::Show
FunctionEnd

Function ScannerHardwarePageLeave
  ${NSD_GetText}  $hEndorsementText $EndorsementText
  ${NSD_GetState} $hImprinterChk    $EnableImprinter
  ${NSD_GetState} $hUVScanChk       $EnableUVScan

  ${If} $EnableImprinter == ${BST_CHECKED}
    StrCpy $EnableImprinter "true"
  ${Else}
    StrCpy $EnableImprinter "false"
  ${EndIf}
  ${If} $EnableUVScan == ${BST_CHECKED}
    StrCpy $EnableUVScan "true"
  ${Else}
    StrCpy $EnableUVScan "false"
  ${EndIf}
  ${If} $EndorsementText == ""
    MessageBox MB_OK|MB_ICONEXCLAMATION "Endorsement text cannot be blank."
    Abort
  ${EndIf}
FunctionEnd

; ═══════════════════════════════════════════════════════════════════════════
; INSTALL SECTION
; ═══════════════════════════════════════════════════════════════════════════
Section "ASTRA Scanner Agent" SecMain
  SectionIn RO

  SetOutPath "$INSTDIR"

  ; Stop + remove existing service (upgrade path)
  SimpleSC::StopService "${APPID}" 1 30
  SimpleSC::RemoveService "${APPID}"

  ; Copy scanner agent exe
  File "..\astra-cts-scanner.exe"

  ; Copy Canon DLLs
  SetOutPath "$INSTDIR\Canon"
  File "Canon\CanoCheetah.dll"
  File "Canon\CanoCheetahRanger.dll"
  File "Canon\CeiIQA.ini"
  SetOutPath "$INSTDIR"

  ; Write config.ini — all values come from the server response, not user input.
  ; branch_id and bank_id are authoritative from the registration code exchange.
  FileOpen $0 "$INSTDIR\config.ini" w
  FileWrite $0 "; ASTRA CTS Scanner Agent — branch configuration$\r$\n"
  FileWrite $0 "; Generated by ASTRA installer ${VERSION}$\r$\n"
  FileWrite $0 "; Branch ID and Bank ID are server-authoritative — do not edit.$\r$\n"
  FileWrite $0 "; Re-run the installer with a new registration code to change branch.$\r$\n"
  FileWrite $0 "$\r$\n"
  FileWrite $0 "[astra]$\r$\n"
  FileWrite $0 "api_url          = $ASTRAApiUrl$\r$\n"
  FileWrite $0 "bank_id          = $BankID$\r$\n"
  FileWrite $0 "bank_ifsc        = $BankIFSC$\r$\n"
  FileWrite $0 "branch_id        = $BranchID$\r$\n"
  FileWrite $0 "; api_token is in token.dat (restricted read access)$\r$\n"
  FileWrite $0 "$\r$\n"
  FileWrite $0 "[scanner]$\r$\n"
  FileWrite $0 "listen_addr          = :9201$\r$\n"
  FileWrite $0 "discovery_mode       = usb$\r$\n"
  FileWrite $0 "mocr_weight          = $ServerMOCRWeight$\r$\n"
  FileWrite $0 "enable_iqa           = true$\r$\n"
  FileWrite $0 "enable_imprinter     = $EnableImprinter$\r$\n"
  FileWrite $0 "enable_uv_scan       = $EnableUVScan$\r$\n"
  FileWrite $0 "endorsement_text     = $EndorsementText$\r$\n"
  FileWrite $0 "http_timeout_seconds = 30$\r$\n"
  FileClose $0

  ; Write token.dat — API token bound to this machine by the server.
  ; Immediately restrict NTFS ACL: only SYSTEM and Administrators can read it.
  FileOpen $0 "$INSTDIR\token.dat" w
  FileWrite $0 "$ApiToken"
  FileClose $0
  AccessControl::DisableFileInheritance "$INSTDIR\token.dat"
  AccessControl::ClearOnFile            "$INSTDIR\token.dat" "(CI)" "FullAccess"
  AccessControl::GrantOnFile            "$INSTDIR\token.dat" "SYSTEM"         "FullAccess"
  AccessControl::GrantOnFile            "$INSTDIR\token.dat" "Administrators" "FullAccess"

  ; Install Windows service — runs as LOCAL SYSTEM, auto-starts with Windows
  SimpleSC::InstallService "${APPID}" \
    "ASTRA CTS Scanner Agent ($BranchName)" \
    "16" "2" \
    "$INSTDIR\astra-cts-scanner.exe" \
    "" "" ""
  Pop $0
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONSTOP \
      "Service installation failed (error $0). Run the installer as Administrator."
    Abort
  ${EndIf}

  SimpleSC::SetServiceDescription "${APPID}" \
    "ASTRA CTS Scanner Agent — Canon CR-120/150 bridge. Branch: $BranchID"

  SimpleSC::StartService "${APPID}" "" 30
  Pop $0
  ${If} $0 != 0
    MessageBox MB_OK|MB_ICONEXCLAMATION \
      "Service installed but failed to start (error $0).$\r$\n\
       Ensure the Canon scanner is connected and powered on, then start manually via services.msc."
  ${EndIf}

  ; Registry — for upgrade detection and Add/Remove Programs
  WriteRegStr   ${REG_ROOT} "${REG_KEY}" "InstallDir" "$INSTDIR"
  WriteRegStr   ${REG_ROOT} "${REG_KEY}" "Version"    "${VERSION}"
  WriteRegStr   ${REG_ROOT} "${REG_KEY}" "BranchID"   "$BranchID"
  WriteRegStr   ${REG_ROOT} "${REG_KEY}" "BankID"     "$BankID"
  WriteRegStr   ${REG_ROOT} "${REG_KEY}" "BankIFSC"   "$BankIFSC"
  WriteRegStr   ${REG_ROOT} "${REG_KEY}" "ApiUrl"     "$ASTRAApiUrl"
  ; Store branch name for display in services.msc and upgrade pre-fill
  WriteRegStr   ${REG_ROOT} "${REG_KEY}" "BranchName" "$BranchName"

  WriteRegStr   ${REG_ROOT} "${REG_UNINST}" "DisplayName"     "${APPNAME} — $BranchName"
  WriteRegStr   ${REG_ROOT} "${REG_UNINST}" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegStr   ${REG_ROOT} "${REG_UNINST}" "Publisher"       "${PUBLISHER}"
  WriteRegStr   ${REG_ROOT} "${REG_UNINST}" "DisplayVersion"  "${VERSION}"
  WriteRegDWORD ${REG_ROOT} "${REG_UNINST}" "NoModify"        1
  WriteRegDWORD ${REG_ROOT} "${REG_UNINST}" "NoRepair"        1

  ; Start Menu — opens scanner health page in browser
  CreateDirectory "$SMPROGRAMS\ASTRA"
  CreateShortcut "$SMPROGRAMS\ASTRA\Scanner Status ($BranchName).lnk" \
    "$WINDIR\System32\rundll32.exe" \
    "url.dll,FileProtocolHandler http://localhost:9201/health" \
    "$INSTDIR\astra-cts-scanner.exe" 0

  WriteUninstaller "$INSTDIR\uninstall.exe"

  DetailPrint "Installed: ${APPNAME} ${VERSION}"
  DetailPrint "Branch: $BranchID ($BranchName)"
  DetailPrint "Bank: $BankID | IFSC: $BankIFSC"
SectionEnd

; ═══════════════════════════════════════════════════════════════════════════
; UNINSTALL
; ═══════════════════════════════════════════════════════════════════════════
Section "Uninstall"
  SimpleSC::StopService   "${APPID}" 1 30
  SimpleSC::RemoveService "${APPID}"

  Delete "$INSTDIR\astra-cts-scanner.exe"
  Delete "$INSTDIR\config.ini"
  Delete "$INSTDIR\token.dat"
  Delete "$INSTDIR\Canon\CanoCheetah.dll"
  Delete "$INSTDIR\Canon\CanoCheetahRanger.dll"
  Delete "$INSTDIR\Canon\CeiIQA.ini"
  RMDir  "$INSTDIR\Canon"
  Delete "$INSTDIR\uninstall.exe"
  RMDir  "$INSTDIR"

  ; Remove Start Menu entry (branch name embedded in shortcut name)
  ReadRegStr $0 ${REG_ROOT} "${REG_KEY}" "BranchName"
  Delete "$SMPROGRAMS\ASTRA\Scanner Status ($0).lnk"
  RMDir  "$SMPROGRAMS\ASTRA"

  DeleteRegKey ${REG_ROOT} "${REG_KEY}"
  DeleteRegKey ${REG_ROOT} "${REG_UNINST}"
SectionEnd
