"""
Generates infra/k8s/monitoring/generated-incident-alerts.yaml from every
messages.yaml key that carries a complete incident: block.

Same relationship to messages.yaml as build_docs.py's CTS_Msg_Taxonomy.html:
mechanically derived, never hand-edited. Rules here can never drift from the
taxonomy doc because both are generated from the exact same source entry.

Invoked automatically by shared/messages/build.py after every successful
build. Can also be run standalone:
    python -m shared.messages.build_alerts

Hand-written PrometheusRule (infra/k8s/monitoring/prometheus-rules.yaml)
covers infrastructure-level signals (Kafka lag, Redis eviction, latency
histograms) that have no messages.yaml key of their own — this file only
ever covers the caught-exception → incident path.
"""
import sys
from pathlib import Path
from typing import Any

import yaml

_DEFAULT_YAML = Path(__file__).parent / "locales" / "messages.yaml"
_DEFAULT_OUTPUT = Path(__file__).parents[2] / "infra" / "k8s" / "monitoring" / "generated-incident-alerts.yaml"

_SEVERITY_TO_PROM = {
    "P0": "critical",
    "P1": "critical",
    "P2": "warning",
    "P3": "warning",
    "P4": "info",
}


def _module_label(key: str) -> str:
    if key.startswith("CTS_"):
        return "cts"
    if key.startswith("EJ_"):
        return "ej"
    return "platform"


def _alert_name(key: str) -> str:
    return key.replace("_", "")


def _build_rule(key: str, entry: dict[str, Any]) -> dict[str, Any]:
    incident = entry["incident"]
    trigger = incident["escalation_trigger"]

    if trigger == "IMMEDIATE":
        expr = f'increase(astra_incident_signal_total{{message_key="{key}"}}[5m]) > 0'
    else:
        threshold = incident["threshold"]
        expr = (
            f'increase(astra_incident_signal_total{{message_key="{key}"}}'
            f'[{threshold["window_seconds"]}s]) > {threshold["count"]}'
        )

    description = f'{entry.get("en", "")} Runbook: {incident.get("runbook_ref", "")}'

    return {
        "alert": _alert_name(key),
        "expr": expr,
        "for": "0s",   # every generated rule fires immediately once its own expr threshold is met —
                       # the grace period, if any, is already baked into the THRESHOLD window itself
        "labels": {
            "severity": _SEVERITY_TO_PROM.get(incident["default_severity"], "warning"),
            "module": _module_label(key),
            "owning_team": incident["owning_team"],
            "incident_class": incident["incident_class"],
        },
        "annotations": {
            "summary": f"{key} — incident signal fired for bank {{{{ $labels.bank_id }}}}",
            "description": description,
        },
    }


def build_alert_rules(yaml_path: Path = _DEFAULT_YAML, output_path: Path = _DEFAULT_OUTPUT) -> None:
    raw = yaml.safe_load(yaml_path.read_text(encoding="utf-8")) or {}

    groups: dict[str, list[dict[str, Any]]] = {}
    for key, entry in raw.items():
        if key.startswith("#") or not isinstance(entry, dict):
            continue
        incident = entry.get("incident")
        if not incident:
            continue
        owning_team = incident.get("owning_team", "unassigned")
        groups.setdefault(owning_team, []).append(_build_rule(key, entry))

    doc = {
        "apiVersion": "monitoring.coreos.com/v1",
        "kind": "PrometheusRule",
        "metadata": {
            "name": "astra-incident-alerts",
            "namespace": "monitoring",
            "labels": {"prometheus": "kube-prometheus", "role": "alert-rules"},
        },
        "spec": {
            "groups": [
                {"name": team, "rules": rules}
                for team, rules in sorted(groups.items())
            ]
        },
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# AUTO-GENERATED by python -m shared.messages.build -- do not edit.\n"
        "# Source of truth: shared/messages/locales/messages.yaml (incident: blocks).\n"
        "# Hand-written infra alerts (Kafka lag, Redis eviction, latency) live in\n"
        "# infra/k8s/monitoring/prometheus-rules.yaml instead.\n"
    )
    body = yaml.dump(doc, sort_keys=False, default_flow_style=False, allow_unicode=True)
    output_path.write_text(header + body, encoding="utf-8")
    total_rules = sum(len(g["rules"]) for g in doc["spec"]["groups"])
    print(f"generated-incident-alerts.yaml written: {output_path}  ({total_rules} rules)")


if __name__ == "__main__":
    yaml_path = Path(sys.argv[1]) if len(sys.argv) > 1 else _DEFAULT_YAML
    output_path = Path(sys.argv[2]) if len(sys.argv) > 2 else _DEFAULT_OUTPUT
    build_alert_rules(yaml_path, output_path)
